"""New DB structure

Revision ID: 085885c7be38
Revises: 
Create Date: 2020-03-13 15:04:40.056692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085885c7be38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('std_offset', sa.Integer(), nullable=True),
    sa.Column('std_name', sa.String(length=64), nullable=True),
    sa.Column('std_abbr', sa.String(length=16), nullable=True),
    sa.Column('dst_abbr', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('time_zone_id', sa.Integer(), nullable=True),
    sa.Column('dst_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['time_zone_id'], ['time_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=240), nullable=True),
    sa.Column('process_time', sa.Time(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('time_zone')
    # ### end Alembic commands ###
