"""Quotes table

Revision ID: 1d8569484296
Revises: b26b8bd3695d
Create Date: 2020-03-09 16:29:24.455369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8569484296'
down_revision = 'b26b8bd3695d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quote', sa.String(length=240), nullable=True),
    sa.Column('process_time', sa.Time(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_timestamp'), 'quotes', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_column('user', 'timestamp')
    op.drop_index(op.f('ix_quotes_timestamp'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
