"""empty message

Revision ID: 229013a04abb
Revises: c7d4ef182efd
Create Date: 2020-03-17 15:20:01.568337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229013a04abb'
down_revision = 'c7d4ef182efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_dst', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_dst')
    # ### end Alembic commands ###
