"""Changed Quotes to Quote for table name

Revision ID: 72350883b897
Revises: 1d8569484296
Create Date: 2020-03-09 16:37:42.485189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72350883b897'
down_revision = '1d8569484296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quote', sa.String(length=240), nullable=True),
    sa.Column('process_time', sa.Time(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_timestamp'), 'quote', ['timestamp'], unique=False)
    op.drop_index('ix_quotes_timestamp', table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quote', sa.VARCHAR(length=240), nullable=True),
    sa.Column('process_time', sa.TIME(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_timestamp', 'quotes', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_quote_timestamp'), table_name='quote')
    op.drop_table('quote')
    # ### end Alembic commands ###
